"use client";
import { useState } from "react";


export default function RadicalsPage() {
  const [selectedRadical, setSelectedRadical] = useState<null | {
    char: string;
    pinyin: string;
    viet: string;
    meaning: string;
    strokes: number;
    origin: string;
    variants: string[];
    examples: { word: string; pinyin: string; meaning: string }[];
  }>(null);
  const [activeTab, setActiveTab] = useState(0); // 0 là tất cả, còn lại là số nét

  const fullRadicalsData = [
    {
      char: "一",
      pinyin: "yī",
      viet: "Nhất",
      meaning: "Số một",
      strokes: 1,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Nhất.",
      variants: ["一"],
      examples: [{ word: "一", pinyin: "yī", meaning: "Số một" }],
    },
    {
      char: "丨",
      pinyin: "gǔn",
      viet: "Cổn",
      meaning: "Nét sổ",
      strokes: 1,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Cổn.",
      variants: ["丨"],
      examples: [{ word: "丨", pinyin: "gǔn", meaning: "Nét sổ" }],
    },
    {
      char: "丶",
      pinyin: "zhǔ",
      viet: "Chủ",
      meaning: "Điểm chấm",
      strokes: 1,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Chủ.",
      variants: ["丶"],
      examples: [{ word: "丶", pinyin: "zhǔ", meaning: "Điểm chấm" }],
    },
    {
      char: "丿",
      pinyin: "piě",
      viet: "Phiệt",
      meaning: "Nét phẩy",
      strokes: 1,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Phiệt.",
      variants: ["丿"],
      examples: [{ word: "丿", pinyin: "piě", meaning: "Nét phẩy" }],
    },
    {
      char: "乙",
      pinyin: "yǐ",
      viet: "Ất",
      meaning: "Nét móc cong",
      strokes: 1,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Ất.",
      variants: ["乙"],
      examples: [{ word: "乙", pinyin: "yǐ", meaning: "Nét móc cong" }],
    },
    {
      char: "亅",
      pinyin: "jué",
      viet: "Quyết",
      meaning: "Nét móc thẳng",
      strokes: 1,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Quyết.",
      variants: ["亅"],
      examples: [{ word: "亅", pinyin: "jué", meaning: "Nét móc thẳng" }],
    },
    {
      char: "二",
      pinyin: "èr",
      viet: "Nhị",
      meaning: "Số hai",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Nhị.",
      variants: ["二"],
      examples: [{ word: "二", pinyin: "èr", meaning: "Số hai" }],
    },
    {
      char: "亠",
      pinyin: "tóu",
      viet: "Đầu",
      meaning: "Nắp đầu",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Đầu.",
      variants: ["亠"],
      examples: [{ word: "亠", pinyin: "tóu", meaning: "Nắp đầu" }],
    },
    {
      char: "人",
      pinyin: "rén",
      viet: "Nhân",
      meaning: "Người",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Nhân.",
      variants: ["人"],
      examples: [{ word: "人", pinyin: "rén", meaning: "Người" }],
    },
    {
      char: "儿",
      pinyin: "ér",
      viet: "Nhi",
      meaning: "Chân người",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Nhi.",
      variants: ["儿"],
      examples: [{ word: "儿", pinyin: "ér", meaning: "Chân người" }],
    },
    {
      char: "入",
      pinyin: "rù",
      viet: "Nhập",
      meaning: "Vào",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Nhập.",
      variants: ["入"],
      examples: [{ word: "入", pinyin: "rù", meaning: "Vào" }],
    },
    {
      char: "八",
      pinyin: "bā",
      viet: "Bát",
      meaning: "Đôi chia tách",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Bát.",
      variants: ["八"],
      examples: [{ word: "八", pinyin: "bā", meaning: "Đôi chia tách" }],
    },
    {
      char: "冂",
      pinyin: "jiōng",
      viet: "Quynh",
      meaning: "Vùng biên",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Quynh.",
      variants: ["冂"],
      examples: [{ word: "冂", pinyin: "jiōng", meaning: "Vùng biên" }],
    },
    {
      char: "冖",
      pinyin: "mì",
      viet: "Mịch",
      meaning: "Che phủ",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Mịch.",
      variants: ["冖"],
      examples: [{ word: "冖", pinyin: "mì", meaning: "Che phủ" }],
    },
    {
      char: "冫",
      pinyin: "bīng",
      viet: "Băng",
      meaning: "Nước đá",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Băng.",
      variants: ["冫"],
      examples: [{ word: "冫", pinyin: "bīng", meaning: "Nước đá" }],
    },
    {
      char: "几",
      pinyin: "jī",
      viet: "Kỷ",
      meaning: "Cái bàn nhỏ",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Kỷ.",
      variants: ["几"],
      examples: [{ word: "几", pinyin: "jī", meaning: "Cái bàn nhỏ" }],
    },
    {
      char: "凵",
      pinyin: "qiǎn",
      viet: "Khảm",
      meaning: "Hộp mở",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Khảm.",
      variants: ["凵"],
      examples: [{ word: "凵", pinyin: "qiǎn", meaning: "Hộp mở" }],
    },
    {
      char: "刀",
      pinyin: "dāo",
      viet: "Đao",
      meaning: "Dao",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Đao.",
      variants: ["刀"],
      examples: [{ word: "刀", pinyin: "dāo", meaning: "Dao" }],
    },
    {
      char: "力",
      pinyin: "lì",
      viet: "Lực",
      meaning: "Sức mạnh",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Lực.",
      variants: ["力"],
      examples: [{ word: "力", pinyin: "lì", meaning: "Sức mạnh" }],
    },
    {
      char: "勹",
      pinyin: "bāo",
      viet: "Bào",
      meaning: "Bao bọc",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Bào.",
      variants: ["勹"],
      examples: [{ word: "勹", pinyin: "bāo", meaning: "Bao bọc" }],
    },
    {
      char: "匕",
      pinyin: "bǐ",
      viet: "Chủy",
      meaning: "Thìa/dao nhỏ",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Chủy.",
      variants: ["匕"],
      examples: [{ word: "匕", pinyin: "bǐ", meaning: "Thìa/dao nhỏ" }],
    },
    {
      char: "匚",
      pinyin: "fāng",
      viet: "Phương",
      meaning: "Hộp chữ nhật",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Phương.",
      variants: ["匚"],
      examples: [{ word: "匚", pinyin: "fāng", meaning: "Hộp chữ nhật" }],
    },
    {
      char: "匸",
      pinyin: "xì",
      viet: "Hệ",
      meaning: "Che giấu",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Hệ.",
      variants: ["匸"],
      examples: [{ word: "匸", pinyin: "xì", meaning: "Che giấu" }],
    },
    {
      char: "十",
      pinyin: "shí",
      viet: "Thập",
      meaning: "Số mười",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thập.",
      variants: ["十"],
      examples: [{ word: "十", pinyin: "shí", meaning: "Số mười" }],
    },
    {
      char: "卜",
      pinyin: "bǔ",
      viet: "Bốc",
      meaning: "Bói toán",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Bốc.",
      variants: ["卜"],
      examples: [{ word: "卜", pinyin: "bǔ", meaning: "Bói toán" }],
    },
    {
      char: "卩",
      pinyin: "jié",
      viet: "Tiết",
      meaning: "Dấu niêm phong",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Tiết.",
      variants: ["卩"],
      examples: [{ word: "卩", pinyin: "jié", meaning: "Dấu niêm phong" }],
    },
    {
      char: "厂",
      pinyin: "chǎn",
      viet: "Hán",
      meaning: "Vách đá",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Hán.",
      variants: ["厂"],
      examples: [{ word: "厂", pinyin: "chǎn", meaning: "Vách đá" }],
    },
    {
      char: "厶",
      pinyin: "sī",
      viet: "Khư",
      meaning: "Riêng tư",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Khư.",
      variants: ["厶"],
      examples: [{ word: "厶", pinyin: "sī", meaning: "Riêng tư" }],
    },
    {
      char: "又",
      pinyin: "yòu",
      viet: "Hựu",
      meaning: "Lại",
      strokes: 2,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Hựu.",
      variants: ["又"],
      examples: [{ word: "又", pinyin: "yòu", meaning: "Lại" }],
    },
    {
      char: "口",
      pinyin: "kǒu",
      viet: "Khẩu",
      meaning: "Miệng",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Khẩu.",
      variants: ["口"],
      examples: [{ word: "口", pinyin: "kǒu", meaning: "Miệng" }],
    },
    {
      char: "囗",
      pinyin: "wéi",
      viet: "Vi",
      meaning: "Khung bao",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Vi.",
      variants: ["囗"],
      examples: [{ word: "囗", pinyin: "wéi", meaning: "Khung bao" }],
    },
    {
      char: "土",
      pinyin: "tǔ",
      viet: "Thổ",
      meaning: "Đất",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thổ.",
      variants: ["土"],
      examples: [{ word: "土", pinyin: "tǔ", meaning: "Đất" }],
    },
    {
      char: "士",
      pinyin: "shì",
      viet: "Sĩ",
      meaning: "Học giả",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Sĩ.",
      variants: ["士"],
      examples: [{ word: "士", pinyin: "shì", meaning: "Học giả" }],
    },
    {
      char: "夂",
      pinyin: "zhī",
      viet: "Truy",
      meaning: "Bước chân",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Truy.",
      variants: ["夂"],
      examples: [{ word: "夂", pinyin: "zhī", meaning: "Bước chân" }],
    },
    {
      char: "夊",
      pinyin: "suī",
      viet: "Thôi",
      meaning: "Bước chậm",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thôi.",
      variants: ["夊"],
      examples: [{ word: "夊", pinyin: "suī", meaning: "Bước chậm" }],
    },
    {
      char: "夕",
      pinyin: "xī",
      viet: "Tịch",
      meaning: "Buổi tối",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Tịch.",
      variants: ["夕"],
      examples: [{ word: "夕", pinyin: "xī", meaning: "Buổi tối" }],
    },
    {
      char: "大",
      pinyin: "dà",
      viet: "Đại",
      meaning: "To lớn",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Đại.",
      variants: ["大"],
      examples: [{ word: "大", pinyin: "dà", meaning: "To lớn" }],
    },
    {
      char: "女",
      pinyin: "nǚ",
      viet: "Nữ",
      meaning: "Nữ giới",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Nữ.",
      variants: ["女"],
      examples: [{ word: "女", pinyin: "nǚ", meaning: "Nữ giới" }],
    },
    {
      char: "子",
      pinyin: "zǐ",
      viet: "Tử",
      meaning: "Con",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Tử.",
      variants: ["子"],
      examples: [{ word: "子", pinyin: "zǐ", meaning: "Con" }],
    },
    {
      char: "宀",
      pinyin: "mián",
      viet: "Miên",
      meaning: "Mái nhà",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Miên.",
      variants: ["宀"],
      examples: [{ word: "宀", pinyin: "mián", meaning: "Mái nhà" }],
    },
    {
      char: "寸",
      pinyin: "cùn",
      viet: "Thốn",
      meaning: "Đơn vị đo",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thốn.",
      variants: ["寸"],
      examples: [{ word: "寸", pinyin: "cùn", meaning: "Đơn vị đo" }],
    },
    {
      char: "小",
      pinyin: "xiǎo",
      viet: "Tiểu",
      meaning: "Nhỏ",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Tiểu.",
      variants: ["小"],
      examples: [{ word: "小", pinyin: "xiǎo", meaning: "Nhỏ" }],
    },
    {
      char: "尢",
      pinyin: "wāng",
      viet: "Uông",
      meaning: "Yếu đuối",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Uông.",
      variants: ["尢"],
      examples: [{ word: "尢", pinyin: "wāng", meaning: "Yếu đuối" }],
    },
    {
      char: "尸",
      pinyin: "shī",
      viet: "Thi",
      meaning: "Xác",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thi.",
      variants: ["尸"],
      examples: [{ word: "尸", pinyin: "shī", meaning: "Xác" }],
    },
    {
      char: "屮",
      pinyin: "chè",
      viet: "Triệt",
      meaning: "Mầm cây",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Triệt.",
      variants: ["屮"],
      examples: [{ word: "屮", pinyin: "chè", meaning: "Mầm cây" }],
    },
    {
      char: "山",
      pinyin: "shān",
      viet: "Sơn",
      meaning: "Núi",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Sơn.",
      variants: ["山"],
      examples: [{ word: "山", pinyin: "shān", meaning: "Núi" }],
    },
    {
      char: "巛",
      pinyin: "chuān",
      viet: "Xuyên",
      meaning: "Dòng nước",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Xuyên.",
      variants: ["巛"],
      examples: [{ word: "巛", pinyin: "chuān", meaning: "Dòng nước" }],
    },
    {
      char: "工",
      pinyin: "gōng",
      viet: "Công",
      meaning: "Công việc",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Công.",
      variants: ["工"],
      examples: [{ word: "工", pinyin: "gōng", meaning: "Công việc" }],
    },
    {
      char: "己",
      pinyin: "jǐ",
      viet: "Kỷ",
      meaning: "Bản thân",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Kỷ.",
      variants: ["己"],
      examples: [{ word: "己", pinyin: "jǐ", meaning: "Bản thân" }],
    },
    {
      char: "巾",
      pinyin: "jīn",
      viet: "Cân",
      meaning: "Khăn",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Cân.",
      variants: ["巾"],
      examples: [{ word: "巾", pinyin: "jīn", meaning: "Khăn" }],
    },
    {
      char: "干",
      pinyin: "gān",
      viet: "Cán",
      meaning: "Thân cây",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Cán.",
      variants: ["干"],
      examples: [{ word: "干", pinyin: "gān", meaning: "Thân cây" }],
    },
    {
      char: "幺",
      pinyin: "yāo",
      viet: "Yêu",
      meaning: "Nhỏ bé",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Yêu.",
      variants: ["幺"],
      examples: [{ word: "幺", pinyin: "yāo", meaning: "Nhỏ bé" }],
    },
    {
      char: "广",
      pinyin: "guǎng",
      viet: "Quảng",
      meaning: "Mái nhà",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Quảng.",
      variants: ["广"],
      examples: [{ word: "广", pinyin: "guǎng", meaning: "Mái nhà" }],
    },
    {
      char: "廴",
      pinyin: "yǐn",
      viet: "Dẫn",
      meaning: "Bước dài",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Dẫn.",
      variants: ["廴"],
      examples: [{ word: "廴", pinyin: "yǐn", meaning: "Bước dài" }],
    },
    {
      char: "廾",
      pinyin: "gǒng",
      viet: "Củng",
      meaning: "Hai tay nâng",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Củng.",
      variants: ["廾"],
      examples: [{ word: "廾", pinyin: "gǒng", meaning: "Hai tay nâng" }],
    },
    {
      char: "弋",
      pinyin: "yì",
      viet: "Dặc",
      meaning: "Bắn tên",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Dặc.",
      variants: ["弋"],
      examples: [{ word: "弋", pinyin: "yì", meaning: "Bắn tên" }],
    },
    {
      char: "弓",
      pinyin: "gōng",
      viet: "Cung",
      meaning: "Cây cung",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Cung.",
      variants: ["弓"],
      examples: [{ word: "弓", pinyin: "gōng", meaning: "Cây cung" }],
    },
    {
      char: "彐",
      pinyin: "jì",
      viet: "Kê",
      meaning: "Đầu lợn",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Kê.",
      variants: ["彐"],
      examples: [{ word: "彐", pinyin: "jì", meaning: "Đầu lợn" }],
    },
    {
      char: "彡",
      pinyin: "shān",
      viet: "Sam",
      meaning: "Lông",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Sam.",
      variants: ["彡"],
      examples: [{ word: "彡", pinyin: "shān", meaning: "Lông" }],
    },
    {
      char: "彳",
      pinyin: "chì",
      viet: "Xích",
      meaning: "Bước chân trái",
      strokes: 3,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Xích.",
      variants: ["彳"],
      examples: [{ word: "彳", pinyin: "chì", meaning: "Bước chân trái" }],
    },
    {
      char: "心",
      pinyin: "xīn",
      viet: "Tâm",
      meaning: "Trái tim",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Tâm.",
      variants: ["心"],
      examples: [{ word: "心", pinyin: "xīn", meaning: "Trái tim" }],
    },
    {
      char: "戈",
      pinyin: "gē",
      viet: "Qua",
      meaning: "Mâu",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Qua.",
      variants: ["戈"],
      examples: [{ word: "戈", pinyin: "gē", meaning: "Mâu" }],
    },
    {
      char: "户",
      pinyin: "hù",
      viet: "Hộ",
      meaning: "Cửa",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Hộ.",
      variants: ["户"],
      examples: [{ word: "户", pinyin: "hù", meaning: "Cửa" }],
    },
    {
      char: "手",
      pinyin: "shǒu",
      viet: "Thủ",
      meaning: "Bàn tay",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thủ.",
      variants: ["手"],
      examples: [{ word: "手", pinyin: "shǒu", meaning: "Bàn tay" }],
    },
    {
      char: "支",
      pinyin: "zhī",
      viet: "Chi",
      meaning: "Cành",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Chi.",
      variants: ["支"],
      examples: [{ word: "支", pinyin: "zhī", meaning: "Cành" }],
    },
    {
      char: "攴",
      pinyin: "pū",
      viet: "Phộc",
      meaning: "Đánh",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Phộc.",
      variants: ["攴"],
      examples: [{ word: "攴", pinyin: "pū", meaning: "Đánh" }],
    },
    {
      char: "文",
      pinyin: "wén",
      viet: "Văn",
      meaning: "Văn chương",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Văn.",
      variants: ["文"],
      examples: [{ word: "文", pinyin: "wén", meaning: "Văn chương" }],
    },
    {
      char: "斗",
      pinyin: "dǒu",
      viet: "Đẩu",
      meaning: "Cái đấu",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Đẩu.",
      variants: ["斗"],
      examples: [{ word: "斗", pinyin: "dǒu", meaning: "Cái đấu" }],
    },
    {
      char: "斤",
      pinyin: "jīn",
      viet: "Cân",
      meaning: "Rìu",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Cân.",
      variants: ["斤"],
      examples: [{ word: "斤", pinyin: "jīn", meaning: "Rìu" }],
    },
    {
      char: "方",
      pinyin: "fāng",
      viet: "Phương",
      meaning: "Hướng",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Phương.",
      variants: ["方"],
      examples: [{ word: "方", pinyin: "fāng", meaning: "Hướng" }],
    },
    {
      char: "无",
      pinyin: "wú",
      viet: "Vô",
      meaning: "Không",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Vô.",
      variants: ["无"],
      examples: [{ word: "无", pinyin: "wú", meaning: "Không" }],
    },
    {
      char: "日",
      pinyin: "rì",
      viet: "Nhật",
      meaning: "Mặt trời",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Nhật.",
      variants: ["日"],
      examples: [{ word: "日", pinyin: "rì", meaning: "Mặt trời" }],
    },
    {
      char: "曰",
      pinyin: "yuē",
      viet: "Viết",
      meaning: "Nói",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Viết.",
      variants: ["曰"],
      examples: [{ word: "曰", pinyin: "yuē", meaning: "Nói" }],
    },
    {
      char: "月",
      pinyin: "yuè",
      viet: "Nguyệt",
      meaning: "Mặt trăng",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Nguyệt.",
      variants: ["月"],
      examples: [{ word: "月", pinyin: "yuè", meaning: "Mặt trăng" }],
    },
    {
      char: "木",
      pinyin: "mù",
      viet: "Mộc",
      meaning: "Cây",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Mộc.",
      variants: ["木"],
      examples: [{ word: "木", pinyin: "mù", meaning: "Cây" }],
    },
    {
      char: "欠",
      pinyin: "qiàn",
      viet: "Khiếm",
      meaning: "Thiếu hụt",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Khiếm.",
      variants: ["欠"],
      examples: [{ word: "欠", pinyin: "qiàn", meaning: "Thiếu hụt" }],
    },
    {
      char: "止",
      pinyin: "zhǐ",
      viet: "Chỉ",
      meaning: "Dừng lại",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Chỉ.",
      variants: ["止"],
      examples: [{ word: "止", pinyin: "zhǐ", meaning: "Dừng lại" }],
    },
    {
      char: "歹",
      pinyin: "dǎi",
      viet: "Đẫy",
      meaning: "Xấu, chết",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Đẫy.",
      variants: ["歹"],
      examples: [{ word: "歹", pinyin: "dǎi", meaning: "Xấu, chết" }],
    },
    {
      char: "殳",
      pinyin: "shū",
      viet: "Thù",
      meaning: "Lao dài",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thù.",
      variants: ["殳"],
      examples: [{ word: "殳", pinyin: "shū", meaning: "Lao dài" }],
    },
    {
      char: "毋",
      pinyin: "wú",
      viet: "Vô",
      meaning: "Không",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Vô.",
      variants: ["毋", "无"],
      examples: [{ word: "毋", pinyin: "wú", meaning: "Không" }],
    },
    {
      char: "比",
      pinyin: "bǐ",
      viet: "Tỷ",
      meaning: "So sánh",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Tỷ.",
      variants: ["比"],
      examples: [{ word: "比", pinyin: "bǐ", meaning: "So sánh" }],
    },
    {
      char: "毛",
      pinyin: "máo",
      viet: "Mao",
      meaning: "Lông",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Mao.",
      variants: ["毛"],
      examples: [{ word: "毛", pinyin: "máo", meaning: "Lông" }],
    },
    {
      char: "氏",
      pinyin: "shì",
      viet: "Thị",
      meaning: "Họ",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thị.",
      variants: ["氏"],
      examples: [{ word: "氏", pinyin: "shì", meaning: "Họ" }],
    },
    {
      char: "气",
      pinyin: "qì",
      viet: "Khí",
      meaning: "Khí",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Khí.",
      variants: ["气"],
      examples: [{ word: "气", pinyin: "qì", meaning: "Khí" }],
    },
    {
      char: "爪",
      pinyin: "zhǎo",
      viet: "Trảo",
      meaning: "Móng vuốt",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Trảo.",
      variants: ["爪"],
      examples: [{ word: "爪", pinyin: "zhǎo", meaning: "Móng vuốt" }],
    },
    {
      char: "父",
      pinyin: "fù",
      viet: "Phụ",
      meaning: "Cha",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Phụ.",
      variants: ["父"],
      examples: [{ word: "父", pinyin: "fù", meaning: "Cha" }],
    },
    {
      char: "爻",
      pinyin: "yáo",
      viet: "Hào",
      meaning: "Hào quẻ",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Hào.",
      variants: ["爻"],
      examples: [{ word: "爻", pinyin: "yáo", meaning: "Hào quẻ" }],
    },
    {
      char: "爿",
      pinyin: "qiáng",
      viet: "Tường",
      meaning: "Mảnh gỗ",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Tường.",
      variants: ["爿"],
      examples: [{ word: "爿", pinyin: "qiáng", meaning: "Mảnh gỗ" }],
    },
    {
      char: "片",
      pinyin: "piàn",
      viet: "Phiến",
      meaning: "Mảnh",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Phiến.",
      variants: ["片"],
      examples: [{ word: "片", pinyin: "piàn", meaning: "Mảnh" }],
    },
    {
      char: "牙",
      pinyin: "yá",
      viet: "Nha",
      meaning: "Răng",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Nha.",
      variants: ["牙"],
      examples: [{ word: "牙", pinyin: "yá", meaning: "Răng" }],
    },
    {
      char: "牛",
      pinyin: "niú",
      viet: "Ngưu",
      meaning: "Trâu bò",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Ngưu.",
      variants: ["牛"],
      examples: [{ word: "牛", pinyin: "niú", meaning: "Trâu bò" }],
    },
    {
      char: "犬",
      pinyin: "quǎn",
      viet: "Khuyển",
      meaning: "Chó",
      strokes: 4,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Khuyển.",
      variants: ["犬"],
      examples: [{ word: "犬", pinyin: "quǎn", meaning: "Chó" }],
    },
    {
      char: "玄",
      pinyin: "xuán",
      viet: "Huyền",
      meaning: "Huyền bí",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Huyền.",
      variants: ["玄"],
      examples: [{ word: "玄", pinyin: "xuán", meaning: "Huyền bí" }],
    },
    {
      char: "玉",
      pinyin: "yù",
      viet: "Ngọc",
      meaning: "Ngọc",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Ngọc.",
      variants: ["玉"],
      examples: [{ word: "玉", pinyin: "yù", meaning: "Ngọc" }],
    },
    {
      char: "瓜",
      pinyin: "guā",
      viet: "Qua",
      meaning: "Quả",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Qua.",
      variants: ["瓜"],
      examples: [{ word: "瓜", pinyin: "guā", meaning: "Quả" }],
    },
    {
      char: "瓦",
      pinyin: "wǎ",
      viet: "Ngõa",
      meaning: "Ngói",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Ngõa.",
      variants: ["瓦"],
      examples: [{ word: "瓦", pinyin: "wǎ", meaning: "Ngói" }],
    },
    {
      char: "甘",
      pinyin: "gān",
      viet: "Cam",
      meaning: "Ngọt",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Cam.",
      variants: ["甘"],
      examples: [{ word: "甘", pinyin: "gān", meaning: "Ngọt" }],
    },
    {
      char: "生",
      pinyin: "shēng",
      viet: "Sinh",
      meaning: "Sống",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Sinh.",
      variants: ["生"],
      examples: [{ word: "生", pinyin: "shēng", meaning: "Sống" }],
    },
    {
      char: "用",
      pinyin: "yòng",
      viet: "Dụng",
      meaning: "Dùng",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Dụng.",
      variants: ["用"],
      examples: [{ word: "用", pinyin: "yòng", meaning: "Dùng" }],
    },
    {
      char: "田",
      pinyin: "tián",
      viet: "Điền",
      meaning: "Ruộng",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Điền.",
      variants: ["田"],
      examples: [{ word: "田", pinyin: "tián", meaning: "Ruộng" }],
    },
    {
      char: "疋",
      pinyin: "pǐ",
      viet: "Thất",
      meaning: "Cuộn vải",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thất.",
      variants: ["疋"],
      examples: [{ word: "疋", pinyin: "pǐ", meaning: "Cuộn vải" }],
    },
    {
      char: "疒",
      pinyin: "nè",
      viet: "Nạch",
      meaning: "Bệnh",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Nạch.",
      variants: ["疒"],
      examples: [{ word: "疒", pinyin: "nè", meaning: "Bệnh" }],
    },
    {
      char: "癶",
      pinyin: "bō",
      viet: "Bát",
      meaning: "Bước chân",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Bát.",
      variants: ["癶"],
      examples: [{ word: "癶", pinyin: "bō", meaning: "Bước chân" }],
    },
    {
      char: "白",
      pinyin: "bái",
      viet: "Bạch",
      meaning: "Trắng",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Bạch.",
      variants: ["白"],
      examples: [{ word: "白", pinyin: "bái", meaning: "Trắng" }],
    },
    {
      char: "皮",
      pinyin: "pí",
      viet: "Bì",
      meaning: "Da",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Bì.",
      variants: ["皮"],
      examples: [{ word: "皮", pinyin: "pí", meaning: "Da" }],
    },
    {
      char: "皿",
      pinyin: "mǐn",
      viet: "Mãnh",
      meaning: "Bát đĩa",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Mãnh.",
      variants: ["皿"],
      examples: [{ word: "皿", pinyin: "mǐn", meaning: "Bát đĩa" }],
    },
    {
      char: "目",
      pinyin: "mù",
      viet: "Mục",
      meaning: "Mắt",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Mục.",
      variants: ["目"],
      examples: [{ word: "目", pinyin: "mù", meaning: "Mắt" }],
    },
    {
      char: "矛",
      pinyin: "máo",
      viet: "Mâu",
      meaning: "Giáo",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Mâu.",
      variants: ["矛"],
      examples: [{ word: "矛", pinyin: "máo", meaning: "Giáo" }],
    },
    {
      char: "矢",
      pinyin: "shǐ",
      viet: "Thỉ",
      meaning: "Mũi tên",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thỉ.",
      variants: ["矢"],
      examples: [{ word: "矢", pinyin: "shǐ", meaning: "Mũi tên" }],
    },
    {
      char: "石",
      pinyin: "shí",
      viet: "Thạch",
      meaning: "Đá",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thạch.",
      variants: ["石"],
      examples: [{ word: "石", pinyin: "shí", meaning: "Đá" }],
    },
    {
      char: "示",
      pinyin: "shì",
      viet: "Thị",
      meaning: "Bàn thờ",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thị.",
      variants: ["示"],
      examples: [{ word: "示", pinyin: "shì", meaning: "Bàn thờ" }],
    },
    {
      char: "禸",
      pinyin: "róu",
      viet: "Nữu",
      meaning: "Dấu chân",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Nữu.",
      variants: ["禸"],
      examples: [{ word: "禸", pinyin: "róu", meaning: "Dấu chân" }],
    },
    {
      char: "禾",
      pinyin: "hé",
      viet: "Hòa",
      meaning: "Lúa",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Hòa.",
      variants: ["禾"],
      examples: [{ word: "禾", pinyin: "hé", meaning: "Lúa" }],
    },
    {
      char: "穴",
      pinyin: "xué",
      viet: "Huyệt",
      meaning: "Hang",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Huyệt.",
      variants: ["穴"],
      examples: [{ word: "穴", pinyin: "xué", meaning: "Hang" }],
    },
    {
      char: "立",
      pinyin: "lì",
      viet: "Lập",
      meaning: "Đứng",
      strokes: 5,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Lập.",
      variants: ["立"],
      examples: [{ word: "立", pinyin: "lì", meaning: "Đứng" }],
    },
    {
      char: "竹",
      pinyin: "zhú",
      viet: "Trúc",
      meaning: "Tre",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Trúc.",
      variants: ["竹"],
      examples: [{ word: "竹", pinyin: "zhú", meaning: "Tre" }],
    },
    {
      char: "米",
      pinyin: "mǐ",
      viet: "Mễ",
      meaning: "Gạo",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Mễ.",
      variants: ["米"],
      examples: [{ word: "米", pinyin: "mǐ", meaning: "Gạo" }],
    },
    {
      char: "纟",
      pinyin: "sī",
      viet: "Mịch",
      meaning: "Sợi tơ",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Mịch.",
      variants: ["纟"],
      examples: [{ word: "纟", pinyin: "sī", meaning: "Sợi tơ" }],
    },
    {
      char: "缶",
      pinyin: "fǒu",
      viet: "Phẫu",
      meaning: "Bình đất",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Phẫu.",
      variants: ["缶"],
      examples: [{ word: "缶", pinyin: "fǒu", meaning: "Bình đất" }],
    },
    {
      char: "网",
      pinyin: "wǎng",
      viet: "Võng",
      meaning: "Lưới",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Võng.",
      variants: ["网"],
      examples: [{ word: "网", pinyin: "wǎng", meaning: "Lưới" }],
    },
    {
      char: "羊",
      pinyin: "yáng",
      viet: "Dương",
      meaning: "Dê",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Dương.",
      variants: ["羊"],
      examples: [{ word: "羊", pinyin: "yáng", meaning: "Dê" }],
    },
    {
      char: "羽",
      pinyin: "yǔ",
      viet: "Vũ",
      meaning: "Lông vũ",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Vũ.",
      variants: ["羽"],
      examples: [{ word: "羽", pinyin: "yǔ", meaning: "Lông vũ" }],
    },
    {
      char: "老",
      pinyin: "lǎo",
      viet: "Lão",
      meaning: "Già",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Lão.",
      variants: ["老"],
      examples: [{ word: "老", pinyin: "lǎo", meaning: "Già" }],
    },
    {
      char: "而",
      pinyin: "ér",
      viet: "Nhi",
      meaning: "Nhưng",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Nhi.",
      variants: ["而"],
      examples: [{ word: "而", pinyin: "ér", meaning: "Nhưng" }],
    },
    {
      char: "耒",
      pinyin: "lěi",
      viet: "Lỗ",
      meaning: "Cày",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Lỗ.",
      variants: ["耒"],
      examples: [{ word: "耒", pinyin: "lěi", meaning: "Cày" }],
    },
    {
      char: "耳",
      pinyin: "ěr",
      viet: "Nhĩ",
      meaning: "Tai",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Nhĩ.",
      variants: ["耳"],
      examples: [{ word: "耳", pinyin: "ěr", meaning: "Tai" }],
    },
    {
      char: "聿",
      pinyin: "yù",
      viet: "Duật",
      meaning: "Bút viết",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Duật.",
      variants: ["聿"],
      examples: [{ word: "聿", pinyin: "yù", meaning: "Bút viết" }],
    },
    {
      char: "肉",
      pinyin: "ròu",
      viet: "Nhục",
      meaning: "Thịt",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Nhục.",
      variants: ["肉"],
      examples: [{ word: "肉", pinyin: "ròu", meaning: "Thịt" }],
    },
    {
      char: "臣",
      pinyin: "chén",
      viet: "Thần",
      meaning: "Quan lại",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thần.",
      variants: ["臣"],
      examples: [{ word: "臣", pinyin: "chén", meaning: "Quan lại" }],
    },
    {
      char: "自",
      pinyin: "zì",
      viet: "Tự",
      meaning: "Tự thân",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Tự.",
      variants: ["自"],
      examples: [{ word: "自", pinyin: "zì", meaning: "Tự thân" }],
    },
    {
      char: "至",
      pinyin: "zhì",
      viet: "Chí",
      meaning: "Đến",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Chí.",
      variants: ["至"],
      examples: [{ word: "至", pinyin: "zhì", meaning: "Đến" }],
    },
    {
      char: "臼",
      pinyin: "jiù",
      viet: "Cữu",
      meaning: "Cối giã",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Cữu.",
      variants: ["臼"],
      examples: [{ word: "臼", pinyin: "jiù", meaning: "Cối giã" }],
    },
    {
      char: "舌",
      pinyin: "shé",
      viet: "Thiệt",
      meaning: "Lưỡi",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thiệt.",
      variants: ["舌"],
      examples: [{ word: "舌", pinyin: "shé", meaning: "Lưỡi" }],
    },
    {
      char: "舛",
      pinyin: "chuǎn",
      viet: "Suyễn",
      meaning: "Lỗi trái phải",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Suyễn.",
      variants: ["舛"],
      examples: [{ word: "舛", pinyin: "chuǎn", meaning: "Lỗi trái phải" }],
    },
    {
      char: "舟",
      pinyin: "zhōu",
      viet: "Chu",
      meaning: "Thuyền",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Chu.",
      variants: ["舟"],
      examples: [{ word: "舟", pinyin: "zhōu", meaning: "Thuyền" }],
    },
    {
      char: "艮",
      pinyin: "gèn",
      viet: "Cấn",
      meaning: "Dừng lại",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Cấn.",
      variants: ["艮"],
      examples: [{ word: "艮", pinyin: "gèn", meaning: "Dừng lại" }],
    },
    {
      char: "色",
      pinyin: "sè",
      viet: "Sắc",
      meaning: "Màu sắc",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Sắc.",
      variants: ["色"],
      examples: [{ word: "色", pinyin: "sè", meaning: "Màu sắc" }],
    },
    {
      char: "艸",
      pinyin: "cǎo",
      viet: "Thảo",
      meaning: "Cỏ",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thảo.",
      variants: ["艸"],
      examples: [{ word: "艸", pinyin: "cǎo", meaning: "Cỏ" }],
    },
    {
      char: "虍",
      pinyin: "hū",
      viet: "Hổ",
      meaning: "Đầu cọp",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Hổ.",
      variants: ["虍"],
      examples: [{ word: "虍", pinyin: "hū", meaning: "Đầu cọp" }],
    },
    {
      char: "虫",
      pinyin: "chóng",
      viet: "Trùng",
      meaning: "Sâu bọ",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Trùng.",
      variants: ["虫"],
      examples: [{ word: "虫", pinyin: "chóng", meaning: "Sâu bọ" }],
    },
    {
      char: "血",
      pinyin: "xuè",
      viet: "Huyết",
      meaning: "Máu",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Huyết.",
      variants: ["血"],
      examples: [{ word: "血", pinyin: "xuè", meaning: "Máu" }],
    },
    {
      char: "行",
      pinyin: "xíng",
      viet: "Hành",
      meaning: "Đi lại",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Hành.",
      variants: ["行"],
      examples: [{ word: "行", pinyin: "xíng", meaning: "Đi lại" }],
    },
    {
      char: "衣",
      pinyin: "yī",
      viet: "Y",
      meaning: "Quần áo",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Y.",
      variants: ["衣"],
      examples: [{ word: "衣", pinyin: "yī", meaning: "Quần áo" }],
    },
    {
      char: "襾",
      pinyin: "yà",
      viet: "Á",
      meaning: "Phủ lên",
      strokes: 6,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Á.",
      variants: ["襾"],
      examples: [{ word: "襾", pinyin: "yà", meaning: "Phủ lên" }],
    },
    {
      char: "見",
      pinyin: "jiàn",
      viet: "Kiến",
      meaning: "Nhìn thấy",
      strokes: 7,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Kiến.",
      variants: ["見"],
      examples: [{ word: "見", pinyin: "jiàn", meaning: "Nhìn thấy" }],
    },
    {
      char: "角",
      pinyin: "jiǎo",
      viet: "Giác",
      meaning: "Sừng",
      strokes: 7,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Giác.",
      variants: ["角"],
      examples: [{ word: "角", pinyin: "jiǎo", meaning: "Sừng" }],
    },
    {
      char: "言",
      pinyin: "yán",
      viet: "Ngôn",
      meaning: "Lời nói",
      strokes: 7,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Ngôn.",
      variants: ["言"],
      examples: [{ word: "言", pinyin: "yán", meaning: "Lời nói" }],
    },
    {
      char: "谷",
      pinyin: "gǔ",
      viet: "Cốc",
      meaning: "Thung lũng",
      strokes: 7,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Cốc.",
      variants: ["谷"],
      examples: [{ word: "谷", pinyin: "gǔ", meaning: "Thung lũng" }],
    },
    {
      char: "豆",
      pinyin: "dòu",
      viet: "Đậu",
      meaning: "Đậu",
      strokes: 7,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Đậu.",
      variants: ["豆"],
      examples: [{ word: "豆", pinyin: "dòu", meaning: "Đậu" }],
    },
    {
      char: "豕",
      pinyin: "shǐ",
      viet: "Thỉ",
      meaning: "Heo",
      strokes: 7,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thỉ.",
      variants: ["豕"],
      examples: [{ word: "豕", pinyin: "shǐ", meaning: "Heo" }],
    },
    {
      char: "豸",
      pinyin: "zhì",
      viet: "Trải",
      meaning: "Động vật có râu",
      strokes: 7,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Trải.",
      variants: ["豸"],
      examples: [{ word: "豸", pinyin: "zhì", meaning: "Động vật có râu" }],
    },
    {
      char: "貝",
      pinyin: "bèi",
      viet: "Bối",
      meaning: "Vật quý",
      strokes: 7,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Bối.",
      variants: ["貝"],
      examples: [{ word: "貝", pinyin: "bèi", meaning: "Vật quý" }],
    },
    {
      char: "赤",
      pinyin: "chì",
      viet: "Xích",
      meaning: "Đỏ",
      strokes: 7,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Xích.",
      variants: ["赤"],
      examples: [{ word: "赤", pinyin: "chì", meaning: "Đỏ" }],
    },
    {
      char: "走",
      pinyin: "zǒu",
      viet: "Tẩu",
      meaning: "Chạy",
      strokes: 7,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Tẩu.",
      variants: ["走"],
      examples: [{ word: "走", pinyin: "zǒu", meaning: "Chạy" }],
    },
    {
      char: "足",
      pinyin: "zú",
      viet: "Túc",
      meaning: "Chân",
      strokes: 7,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Túc.",
      variants: ["足"],
      examples: [{ word: "足", pinyin: "zú", meaning: "Chân" }],
    },
    {
      char: "身",
      pinyin: "shēn",
      viet: "Thân",
      meaning: "Cơ thể",
      strokes: 7,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thân.",
      variants: ["身"],
      examples: [{ word: "身", pinyin: "shēn", meaning: "Cơ thể" }],
    },
    {
      char: "車",
      pinyin: "chē",
      viet: "Xa",
      meaning: "Xe",
      strokes: 7,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Xa.",
      variants: ["車"],
      examples: [{ word: "車", pinyin: "chē", meaning: "Xe" }],
    },
    {
      char: "辛",
      pinyin: "xīn",
      viet: "Tân",
      meaning: "Cay",
      strokes: 7,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Tân.",
      variants: ["辛"],
      examples: [{ word: "辛", pinyin: "xīn", meaning: "Cay" }],
    },
    {
      char: "辰",
      pinyin: "chén",
      viet: "Thần",
      meaning: "Thời gian",
      strokes: 7,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thần.",
      variants: ["辰"],
      examples: [{ word: "辰", pinyin: "chén", meaning: "Thời gian" }],
    },
    {
      char: "辵",
      pinyin: "chuò",
      viet: "Sách",
      meaning: "Bước đi",
      strokes: 7,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Sách.",
      variants: ["辵"],
      examples: [{ word: "辵", pinyin: "chuò", meaning: "Bước đi" }],
    },
    {
      char: "邑",
      pinyin: "yì",
      viet: "Ấp",
      meaning: "Thành thị",
      strokes: 7,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Ấp.",
      variants: ["邑"],
      examples: [{ word: "邑", pinyin: "yì", meaning: "Thành thị" }],
    },
    {
      char: "酉",
      pinyin: "yǒu",
      viet: "Dậu",
      meaning: "Nho",
      strokes: 7,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Dậu.",
      variants: ["酉"],
      examples: [{ word: "酉", pinyin: "yǒu", meaning: "Nho" }],
    },
    {
      char: "釆",
      pinyin: "biàn",
      viet: "Biện",
      meaning: "Phân biệt",
      strokes: 7,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Biện.",
      variants: ["釆"],
      examples: [{ word: "釆", pinyin: "biàn", meaning: "Phân biệt" }],
    },
    {
      char: "里",
      pinyin: "lǐ",
      viet: "Lý",
      meaning: "Làng xóm",
      strokes: 7,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Lý.",
      variants: ["里"],
      examples: [{ word: "里", pinyin: "lǐ", meaning: "Làng xóm" }],
    },
    {
      char: "金",
      pinyin: "jīn",
      viet: "Kim",
      meaning: "Kim loại",
      strokes: 8,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Kim.",
      variants: ["金"],
      examples: [{ word: "金", pinyin: "jīn", meaning: "Kim loại" }],
    },
    {
      char: "長",
      pinyin: "cháng",
      viet: "Trường",
      meaning: "Dài",
      strokes: 8,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Trường.",
      variants: ["長"],
      examples: [{ word: "長", pinyin: "cháng", meaning: "Dài" }],
    },
    {
      char: "門",
      pinyin: "mén",
      viet: "Môn",
      meaning: "Cửa",
      strokes: 8,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Môn.",
      variants: ["門"],
      examples: [{ word: "門", pinyin: "mén", meaning: "Cửa" }],
    },
    {
      char: "阜",
      pinyin: "fù",
      viet: "Phụ",
      meaning: "Đồi",
      strokes: 8,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Phụ.",
      variants: ["阜"],
      examples: [{ word: "阜", pinyin: "fù", meaning: "Đồi" }],
    },
    {
      char: "隶",
      pinyin: "dài",
      viet: "Đãi",
      meaning: "Nô lệ",
      strokes: 8,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Đãi.",
      variants: ["隶"],
      examples: [{ word: "隶", pinyin: "dài", meaning: "Nô lệ" }],
    },
    {
      char: "隹",
      pinyin: "zhuī",
      viet: "Chuy",
      meaning: "Chim nhỏ",
      strokes: 8,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Chuy.",
      variants: ["隹"],
      examples: [{ word: "隹", pinyin: "zhuī", meaning: "Chim nhỏ" }],
    },
    {
      char: "雨",
      pinyin: "yǔ",
      viet: "Vũ",
      meaning: "Mưa",
      strokes: 8,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Vũ.",
      variants: ["雨"],
      examples: [{ word: "雨", pinyin: "yǔ", meaning: "Mưa" }],
    },
    {
      char: "青",
      pinyin: "qīng",
      viet: "Thanh",
      meaning: "Xanh",
      strokes: 8,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thanh.",
      variants: ["青"],
      examples: [{ word: "青", pinyin: "qīng", meaning: "Xanh" }],
    },
    {
      char: "非",
      pinyin: "fēi",
      viet: "Phi",
      meaning: "Sai",
      strokes: 8,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Phi.",
      variants: ["非"],
      examples: [{ word: "非", pinyin: "fēi", meaning: "Sai" }],
    },
    {
      char: "面",
      pinyin: "miàn",
      viet: "Diện",
      meaning: "Mặt",
      strokes: 8,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Diện.",
      variants: ["面"],
      examples: [{ word: "面", pinyin: "miàn", meaning: "Mặt" }],
    },
    {
      char: "革",
      pinyin: "gé",
      viet: "Cách",
      meaning: "Da thú",
      strokes: 9,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Cách.",
      variants: ["革"],
      examples: [{ word: "革", pinyin: "gé", meaning: "Da thú" }],
    },
    {
      char: "韋",
      pinyin: "wéi",
      viet: "Vi",
      meaning: "Da mềm",
      strokes: 9,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Vi.",
      variants: ["韋"],
      examples: [{ word: "韋", pinyin: "wéi", meaning: "Da mềm" }],
    },
    {
      char: "韭",
      pinyin: "jiǔ",
      viet: "Cửu",
      meaning: "Hành lá",
      strokes: 9,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Cửu.",
      variants: ["韭"],
      examples: [{ word: "韭", pinyin: "jiǔ", meaning: "Hành lá" }],
    },
    {
      char: "音",
      pinyin: "yīn",
      viet: "Âm",
      meaning: "Âm thanh",
      strokes: 9,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Âm.",
      variants: ["音"],
      examples: [{ word: "音", pinyin: "yīn", meaning: "Âm thanh" }],
    },
    {
      char: "頁",
      pinyin: "yè",
      viet: "Hiệt",
      meaning: "Trang giấy",
      strokes: 9,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Hiệt.",
      variants: ["頁"],
      examples: [{ word: "頁", pinyin: "yè", meaning: "Trang giấy" }],
    },
    {
      char: "風",
      pinyin: "fēng",
      viet: "Phong",
      meaning: "Gió",
      strokes: 9,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Phong.",
      variants: ["風"],
      examples: [{ word: "風", pinyin: "fēng", meaning: "Gió" }],
    },
    {
      char: "飛",
      pinyin: "fēi",
      viet: "Phi",
      meaning: "Bay",
      strokes: 9,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Phi.",
      variants: ["飛"],
      examples: [{ word: "飛", pinyin: "fēi", meaning: "Bay" }],
    },
    {
      char: "食",
      pinyin: "shí",
      viet: "Thực",
      meaning: "Ăn",
      strokes: 9,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thực.",
      variants: ["食"],
      examples: [{ word: "食", pinyin: "shí", meaning: "Ăn" }],
    },
    {
      char: "首",
      pinyin: "shǒu",
      viet: "Thủ",
      meaning: "Đầu",
      strokes: 9,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thủ.",
      variants: ["首"],
      examples: [{ word: "首", pinyin: "shǒu", meaning: "Đầu" }],
    },
    {
      char: "香",
      pinyin: "xiāng",
      viet: "Hương",
      meaning: "Mùi thơm",
      strokes: 9,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Hương.",
      variants: ["香"],
      examples: [{ word: "香", pinyin: "xiāng", meaning: "Mùi thơm" }],
    },
    {
      char: "馬",
      pinyin: "mǎ",
      viet: "Mã",
      meaning: "Ngựa",
      strokes: 10,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Mã.",
      variants: ["馬"],
      examples: [{ word: "馬", pinyin: "mǎ", meaning: "Ngựa" }],
    },
    {
      char: "骨",
      pinyin: "gǔ",
      viet: "Cốt",
      meaning: "Xương",
      strokes: 10,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Cốt.",
      variants: ["骨"],
      examples: [{ word: "骨", pinyin: "gǔ", meaning: "Xương" }],
    },
    {
      char: "高",
      pinyin: "gāo",
      viet: "Cao",
      meaning: "Cao",
      strokes: 10,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Cao.",
      variants: ["高"],
      examples: [{ word: "高", pinyin: "gāo", meaning: "Cao" }],
    },
    {
      char: "髟",
      pinyin: "biāo",
      viet: "Tiêu",
      meaning: "Tóc dài",
      strokes: 10,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Tiêu.",
      variants: ["髟"],
      examples: [{ word: "髟", pinyin: "biāo", meaning: "Tóc dài" }],
    },
    {
      char: "鬥",
      pinyin: "dòu",
      viet: "Đấu",
      meaning: "Đấu tranh",
      strokes: 10,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Đấu.",
      variants: ["鬥"],
      examples: [{ word: "鬥", pinyin: "dòu", meaning: "Đấu tranh" }],
    },
    {
      char: "鬯",
      pinyin: "chàng",
      viet: "Sưởng",
      meaning: "Rượu lễ",
      strokes: 10,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Sưởng.",
      variants: ["鬯"],
      examples: [{ word: "鬯", pinyin: "chàng", meaning: "Rượu lễ" }],
    },
    {
      char: "鬲",
      pinyin: "gé",
      viet: "Cách",
      meaning: "Nồi đất",
      strokes: 10,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Cách.",
      variants: ["鬲"],
      examples: [{ word: "鬲", pinyin: "gé", meaning: "Nồi đất" }],
    },
    {
      char: "鬼",
      pinyin: "guǐ",
      viet: "Quỷ",
      meaning: "Ma quỷ",
      strokes: 10,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Quỷ.",
      variants: ["鬼"],
      examples: [{ word: "鬼", pinyin: "guǐ", meaning: "Ma quỷ" }],
    },
    {
      char: "魚",
      pinyin: "yú",
      viet: "Ngư",
      meaning: "Cá",
      strokes: 11,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Ngư.",
      variants: ["魚"],
      examples: [{ word: "魚", pinyin: "yú", meaning: "Cá" }],
    },
    {
      char: "鳥",
      pinyin: "niǎo",
      viet: "Điểu",
      meaning: "Chim",
      strokes: 11,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Điểu.",
      variants: ["鳥"],
      examples: [{ word: "鳥", pinyin: "niǎo", meaning: "Chim" }],
    },
    {
      char: "鹿",
      pinyin: "lù",
      viet: "Lộc",
      meaning: "Hươu",
      strokes: 11,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Lộc.",
      variants: ["鹿"],
      examples: [{ word: "鹿", pinyin: "lù", meaning: "Hươu" }],
    },
    {
      char: "麦",
      pinyin: "mài",
      viet: "Mạch",
      meaning: "Lúa mạch",
      strokes: 11,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Mạch.",
      variants: ["麦"],
      examples: [{ word: "麦", pinyin: "mài", meaning: "Lúa mạch" }],
    },
    {
      char: "麻",
      pinyin: "má",
      viet: "Ma",
      meaning: "Hạt gai",
      strokes: 11,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Ma.",
      variants: ["麻"],
      examples: [{ word: "麻", pinyin: "má", meaning: "Hạt gai" }],
    },
    {
      char: "黃",
      pinyin: "huáng",
      viet: "Hoàng",
      meaning: "Vàng",
      strokes: 12,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Hoàng.",
      variants: ["黃"],
      examples: [{ word: "黃", pinyin: "huáng", meaning: "Vàng" }],
    },
    {
      char: "黍",
      pinyin: "shǔ",
      viet: "Thử",
      meaning: "Lúa mì",
      strokes: 12,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thử.",
      variants: ["黍"],
      examples: [{ word: "黍", pinyin: "shǔ", meaning: "Lúa mì" }],
    },
    {
      char: "黑",
      pinyin: "hēi",
      viet: "Hắc",
      meaning: "Đen",
      strokes: 12,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Hắc.",
      variants: ["黑"],
      examples: [{ word: "黑", pinyin: "hēi", meaning: "Đen" }],
    },
    {
      char: "黹",
      pinyin: "zhǐ",
      viet: "Chỉ",
      meaning: "Thêu thùa",
      strokes: 13,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Chỉ.",
      variants: ["黹"],
      examples: [{ word: "黹", pinyin: "zhǐ", meaning: "Thêu thùa" }],
    },
    {
      char: "黽",
      pinyin: "mǐn",
      viet: "Mãnh",
      meaning: "Ếch",
      strokes: 13,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Mãnh.",
      variants: ["黽"],
      examples: [{ word: "黽", pinyin: "mǐn", meaning: "Ếch" }],
    },
    {
      char: "鼎",
      pinyin: "dǐng",
      viet: "Đỉnh",
      meaning: "Nồi ba chân",
      strokes: 13,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Đỉnh.",
      variants: ["鼎"],
      examples: [{ word: "鼎", pinyin: "dǐng", meaning: "Nồi ba chân" }],
    },
    {
      char: "鼓",
      pinyin: "gǔ",
      viet: "Cổ",
      meaning: "Trống",
      strokes: 13,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Cổ.",
      variants: ["鼓"],
      examples: [{ word: "鼓", pinyin: "gǔ", meaning: "Trống" }],
    },
    {
      char: "鼠",
      pinyin: "shǔ",
      viet: "Thử",
      meaning: "Chuột",
      strokes: 13,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Thử.",
      variants: ["鼠"],
      examples: [{ word: "鼠", pinyin: "shǔ", meaning: "Chuột" }],
    },
    {
      char: "鼻",
      pinyin: "bí",
      viet: "Tỵ",
      meaning: "Mũi",
      strokes: 14,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Tỵ.",
      variants: ["鼻"],
      examples: [{ word: "鼻", pinyin: "bí", meaning: "Mũi" }],
    },
    {
      char: "齊",
      pinyin: "qí",
      viet: "Tề",
      meaning: "Ngăn nắp",
      strokes: 14,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Tề.",
      variants: ["齊"],
      examples: [{ word: "齊", pinyin: "qí", meaning: "Ngăn nắp" }],
    },
    {
      char: "齒",
      pinyin: "chǐ",
      viet: "Xỉ",
      meaning: "Răng",
      strokes: 15,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Xỉ.",
      variants: ["齒"],
      examples: [{ word: "齒", pinyin: "chǐ", meaning: "Răng" }],
    },
    {
      char: "龍",
      pinyin: "lóng",
      viet: "Long",
      meaning: "Rồng",
      strokes: 16,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Long.",
      variants: ["龍"],
      examples: [{ word: "龍", pinyin: "lóng", meaning: "Rồng" }],
    },
    {
      char: "龜",
      pinyin: "guī",
      viet: "Quy",
      meaning: "Rùa",
      strokes: 16,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Quy.",
      variants: ["龜"],
      examples: [{ word: "龜", pinyin: "guī", meaning: "Rùa" }],
    },
    {
      char: "龠",
      pinyin: "yuè",
      viet: "Duyệt",
      meaning: "Sáo",
      strokes: 17,
      origin: "Hình dáng và ý nghĩa cơ bản của bộ thủ Duyệt.",
      variants: ["龠"],
      examples: [{ word: "龠", pinyin: "yuè", meaning: "Sáo" }],
    },
  ];

  const filteredRadicals = activeTab === 0
    ? fullRadicalsData
    : fullRadicalsData.filter((r) => r.strokes === activeTab);

  const strokeTabs = [0, ...Array.from(new Set(fullRadicalsData.map((r) => r.strokes))).sort((a, b) => a - b)];

  return (
    <div className="min-h-screen bg-[#fcfcfc] pb-20">
      
      {/* Header */}
      <div className="bg-gradient-to-r from-[#b91c1c] to-[#7f1d1d] py-16 px-6 text-white text-center shadow-lg">
        <h1 className="text-4xl font-black mb-3 tracking-tighter">214 BỘ THỦ TIẾNG TRUNG</h1>
        <p className="opacity-90 font-medium text-red-100">Học gốc rễ để thông thạo vạn chữ Hán</p>
      </div>

      <main className="max-w-7xl mx-auto px-6 py-10">
        
        {/* Thanh lọc số nét (Tabs) */}
        <div className="flex flex-wrap justify-center gap-2 mb-12 sticky top-20 z-40 bg-[#fcfcfc]/80 backdrop-blur-md py-4">
          <button
            onClick={() => setActiveTab(0)}
            className={activeTab === 0 ? "px-5 py-2 rounded-full text-xs font-bold transition-all bg-red-600 text-white shadow-lg" : "px-5 py-2 rounded-full text-xs font-bold transition-all bg-white border text-gray-500 hover:border-red-300"}
          >
            Tất cả
          </button>
          {strokeTabs.slice(1).map((n) => (
            <button
              key={n}
              onClick={() => setActiveTab(n)}
              className={activeTab === n ? "px-5 py-2 rounded-full text-xs font-bold transition-all bg-red-600 text-white shadow-lg" : "px-5 py-2 rounded-full text-xs font-bold transition-all bg-white border text-gray-500 hover:border-red-300"}
            >
              {n} nét
            </button>
          ))}
        </div>

        {/* Danh sách hiển thị */}
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-5">
          {filteredRadicals.map((item, index) => (
            <div
              key={index}
              onClick={() => setSelectedRadical(item)}
              className="bg-white border border-gray-100 p-6 rounded-2xl shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all cursor-pointer text-center group"
            >
              <div className="text-5xl font-serif text-gray-800 mb-3 group-hover:text-red-600 transition-colors">
                {item.char}
              </div>
              <div className="text-xs font-black text-red-600 uppercase tracking-widest">{item.viet}</div>
              <div className="text-[10px] text-gray-400 mt-1 uppercase">{item.pinyin}</div>
            </div>
          ))}
        </div>

        {/* Modal chi tiết (giống như bài trước nhưng căn chỉnh đẹp hơn) */}
        {selectedRadical && (
          <div className="fixed inset-0 bg-black/70 backdrop-blur-md flex items-center justify-center z-[100] p-4 overflow-y-auto">
            <div className="bg-white w-full max-w-xl rounded-[2.5rem] overflow-hidden shadow-2xl animate-in zoom-in duration-300 my-auto">
              {/* Header Modal */}
              <div className="bg-red-600 p-10 text-white relative">
                <button
                  onClick={() => setSelectedRadical(null)}
                  className="absolute top-6 right-6 w-10 h-10 flex items-center justify-center rounded-full bg-white/20 hover:bg-white/40 transition-colors text-2xl"
                >
                  ×
                </button>
                <div className="flex items-center gap-8">
                  <div className="text-8xl font-serif">{selectedRadical.char}</div>
                  <div>
                    <h2 className="text-3xl font-black uppercase">{selectedRadical.viet}</h2>
                    <p className="text-red-100 font-medium">Bộ thứ {fullRadicalsData.indexOf(selectedRadical) + 1} / 214</p>
                  </div>
                </div>
              </div>

              {/* Body Modal */}
              <div className="p-10 space-y-8">
                <div>
                  <h4 className="text-[10px] font-black text-red-600 uppercase tracking-[0.2em] mb-3">Nguồn gốc & Biến thể</h4>
                  <p className="text-gray-700 leading-relaxed italic border-l-4 border-red-100 pl-4">{selectedRadical.origin}</p>
                  <div className="mt-4 flex gap-2 flex-wrap">
                    {selectedRadical.variants.map((v) => (
                      <span key={v} className="px-3 py-1 bg-gray-100 rounded text-sm font-bold text-gray-600">Biến thể: {v}</span>
                    ))}
                  </div>
                </div>

                <div>
                  <h4 className="text-[10px] font-black text-red-600 uppercase tracking-[0.2em] mb-4">Ví dụ ghép chữ</h4>
                  <div className="grid grid-cols-1 gap-3">
                    {selectedRadical.examples.map((ex, i) => (
                      <div key={i} className="flex items-center gap-4 p-4 bg-gray-50 rounded-2xl hover:bg-red-50 transition-colors border border-transparent hover:border-red-100">
                        <span className="text-4xl font-serif text-gray-800">{ex.word}</span>
                        <div>
                          <div className="font-bold text-gray-900">{ex.pinyin}</div>
                          <div className="text-sm text-gray-500">{ex.meaning}</div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}